language: bash

services:
  - docker

script:
  - ./build.sh
  - ./extract-psol-archive.sh
  - ./docker-login.sh
  - ./upload-docker.sh

deploy:
  - provider: releases
    api_key: $GITHUB_ACCESS_TOKEN
    overwrite: true
    skip_cleanup: true
    file_glob: true
    file:
      - psol.tar.gz
    on:
      tags: true
